spring.application.name=pvge

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.docker.compose.enabled=false

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
jwt.secret=${JWT_SECRET}
